name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build --file Dockerfile --tag my-node-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag my-node-app $DOCKER_USERNAME/my-node-app
        docker push $DOCKER_USERNAME/my-node-app

    - name: Terraform Init
      uses: hashicorp/terraform-setup-actions@v1

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Get Instance IP
      run: echo ::set-env name=INSTANCE_IP::$(terraform output instance_ip)

    - name: Run Integration Tests
      run: |
        curl http://$INSTANCE_IP/
